### ISSUE TITLE
There is numpy interface problem on MacOS with gcc 9 and python 3

### ISSUE THREAD

**Issue by AlexeyPechnikov** [tum-pbs/reconstructScalarFlows#1]
This error raises with many different numpy versions from 1.15 and to the recent one:

```Loading script 'simpleplume.py'
Generating 3x 128^3 noise tile 
RuntimeError: FATAL: module compiled as little endian, but detected different endianness at runtime
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "simpleplume.py", line 138, in <module>
    saveVisGrid(density, denNpy, 'density_%06d.npz'%t,  drawKind['den3D'], 2.5)
  File "simpleplume.py", line 41, in saveVisGrid
    copyGridToArrayReal(grid, npy)
SystemError: <built-in function copyGridToArrayReal> returned a result with an error set
Script finished.
```

**Comment by AlexeyPechnikov** [comment]
```
brew install --build-from-source numpy

python3 -c 'import numpy; print (numpy.__version__)'
1.18.1

sudo dtruss ./manta simpleplume.py 0 100 1 2>&1|grep -i multiarray

stat64("/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/multiarray.py\0", 0x7FFEEF5327C0, 0x0)		 = 0 0
stat64("/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/multiarray.py\0", 0x7FFEEF532FA0, 0x0)		 = 0 0
open("/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/__pycache__/multiarray.cpython-37.pyc\0", 0x1000000, 0x1B6)		 = 4 0
stat64("/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so\0", 0x7FFEEF52FE70, 0x0)		 = 0 0
stat64("/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so\0", 0x7FFEEF52F0A0, 0x0)		 = 0 0
stat64("/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so\0", 0x7FFEEF52F4E0, 0x0)		 = 0 0
open("/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so\0", 0x0, 0x0)		 = 4 0
stat64("/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/_multiarray_tests.cpython-37m-darwin.so\0", 0x7FFEEF531350, 0x0)		 = 0 0
stat64("/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/_multiarray_tests.cpython-37m-darwin.so\0", 0x7FFEEF530580, 0x0)		 = 0 0
stat64("/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/_multiarray_tests.cpython-37m-darwin.so\0", 0x7FFEEF5309C0, 0x0)		 = 0 0
open("/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/_multiarray_tests.cpython-37m-darwin.so\0", 0x0, 0x0)		 = 4 0
ImportError: numpy.core.multiarray failed to import
```

**Comment by y-zheng18** [comment]
Hi, 

Have you solved the problem?
